// <auto-generated />
using System;
using BookingHotel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingHotel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706084129_init_aggregate_booking")]
    partial class init_aggregate_booking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingHotel.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalNight")
                        .HasColumnType("integer")
                        .HasColumnName("total_night");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BookingHotel.Domain.Bookings.Booking", b =>
                {
                    b.OwnsMany("BookingHotel.Domain.Bookings.BookedRoom", "BookedRooms", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CheckInDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("check_in_date");

                            b1.Property<DateTime>("CheckOutDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("check_out_date");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("MaxCapacitySnapshot")
                                .HasColumnType("integer")
                                .HasColumnName("max_capacity_snapshot");

                            b1.Property<decimal>("PricePerNightSnapshot")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_per_night_snapshot");

                            b1.Property<string>("RoomId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("room_id");

                            b1.Property<string>("RoomNumberSnapshot")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("room_number_snapshot");

                            b1.Property<string>("RoomTypeSnapshot")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("room_type_snapshot");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("booking_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("booking_id");

                            b1.ToTable("booked_rooms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("booking_id");

                            b1.OwnsMany("BookingHotel.Domain.Bookings.GuestStay", "GuestStays", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTime>("DateOfBirth")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("date_of_birth");

                                    b2.Property<string>("FullName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("full_name");

                                    b2.Property<string>("IdNumber")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("id_number");

                                    b2.Property<bool>("IsAdult")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_adult");

                                    b2.Property<string>("Nationality")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("nationality");

                                    b2.Property<Guid>("booked_room_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("booked_room_id");

                                    b2.ToTable("guest_stays", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("booked_room_id");
                                });

                            b1.Navigation("GuestStays");
                        });

                    b.Navigation("BookedRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
